Repository TeamSobokSobok/SobokSobok-Server, pull requests merged in 2024-07, with the labels that each got.

#144 [Feat]: 회원가입 및 로그인 시 platform 필드 추가
  src/main/java/io/sobok/SobokSobok/auth/application/SocialService.java
  src/main/java/io/sobok/SobokSobok/auth/domain/Platform.java
  src/main/java/io/sobok/SobokSobok/auth/domain/User.java
  src/main/java/io/sobok/SobokSobok/auth/ui/AuthController.java
  src/main/java/io/sobok/SobokSobok/auth/ui/dto/SocialLoginRequest.java
  src/main/java/io/sobok/SobokSobok/auth/ui/dto/SocialSignupRequest.java
Labels: 🌱 승헌, 🔥 Feature, ☠️ High Priority

#147 RELEASE 2024/07/07
  README.md
  build.gradle
  src/main/java/io/sobok/SobokSobok/auth/application/SocialService.java
  src/main/java/io/sobok/SobokSobok/auth/domain/Platform.java
  src/main/java/io/sobok/SobokSobok/auth/domain/User.java
  src/main/java/io/sobok/SobokSobok/auth/ui/AuthController.java
  src/main/java/io/sobok/SobokSobok/auth/ui/dto/SocialLoginRequest.java
  src/main/java/io/sobok/SobokSobok/auth/ui/dto/SocialSignupRequest.java
  src/main/java/io/sobok/SobokSobok/config/SQSConfig.java
  src/main/java/io/sobok/SobokSobok/external/aws/sqs/SQSMessageSender.java
  src/main/java/io/sobok/SobokSobok/external/aws/sqs/SQSPushNotificationRequest.java
Labels: 🌱 승헌, 🍀 수현, 🔥 Feature, 🚀 Release, ☠️ High Priority

#148 [Feat]: 스티커 이미지 업로드 API 구현
  build.gradle
  src/main/java/io/sobok/SobokSobok/config/SecurityConfig.java
  src/main/java/io/sobok/SobokSobok/exception/ErrorCode.java
  src/main/java/io/sobok/SobokSobok/exception/SuccessCode.java
  src/main/java/io/sobok/SobokSobok/external/aws/s3/S3Service.java
  src/main/java/io/sobok/SobokSobok/sticker/application/StickerService.java
  src/main/java/io/sobok/SobokSobok/sticker/domain/Sticker.java
  src/main/java/io/sobok/SobokSobok/sticker/ui/StickerController.java
Labels: 🍀 수현, 🔥 Feature, ☠️ High Priority

#149 Release
  build.gradle
  src/main/java/io/sobok/SobokSobok/config/SecurityConfig.java
  src/main/java/io/sobok/SobokSobok/exception/ErrorCode.java
  src/main/java/io/sobok/SobokSobok/exception/SuccessCode.java
  src/main/java/io/sobok/SobokSobok/external/aws/s3/S3Service.java
  src/main/java/io/sobok/SobokSobok/sticker/application/StickerService.java
  src/main/java/io/sobok/SobokSobok/sticker/domain/Sticker.java
  src/main/java/io/sobok/SobokSobok/sticker/ui/StickerController.java
Labels: 🌱 승헌, 🍀 수현, 🔥 Feature, 🚀 Release, ☠️ High Priority

#151 [Feat]: 복약 일정 조회 시 스티커 파라미터 추가
  src/main/java/io/sobok/SobokSobok/pill/infrastructure/PillScheduleQueryRepository.java
  src/main/java/io/sobok/SobokSobok/pill/ui/dto/PillScheduleInfo.java
  src/main/java/io/sobok/SobokSobok/pill/ui/dto/StickerInfo.java
Labels: 🍀 수현, 🔥 Feature, ☠️ High Priority

#155 [Feat]: 약 수정 API 구현
  src/main/java/io/sobok/SobokSobok/exception/SuccessCode.java
  src/main/java/io/sobok/SobokSobok/pill/application/PillService.java
  src/main/java/io/sobok/SobokSobok/pill/domain/Pill.java
  src/main/java/io/sobok/SobokSobok/pill/ui/PillController.java
  src/main/java/io/sobok/SobokSobok/pill/ui/dto/PillUpdateRequest.java
  src/main/java/io/sobok/SobokSobok/utils/PillUtil.java
Labels: 🌱 승헌, 🔥 Feature, ☠️ High Priority
