Repository TeamSobokSobok/SobokSobok-Server, pull requests merged in 2024-03, with the labels that each got.

#97 [Feat]: 회원탈퇴시 이유 받기 API 추가
  src/main/java/io/sobok/SobokSobok/auth/application/AuthService.java
  src/main/java/io/sobok/SobokSobok/auth/domain/User.java
  src/main/java/io/sobok/SobokSobok/auth/ui/AuthController.java
  src/main/java/io/sobok/SobokSobok/auth/ui/dto/LeaveRequest.java
Labels: 🌱 승헌, 🔥 Feature, 🚀 Release, ☠️ High Priority

#98 Release
  src/main/java/io/sobok/SobokSobok/auth/application/AuthService.java
  src/main/java/io/sobok/SobokSobok/auth/domain/User.java
  src/main/java/io/sobok/SobokSobok/auth/ui/AuthController.java
  src/main/java/io/sobok/SobokSobok/auth/ui/dto/LeaveRequest.java
Labels: 🚀 Release

#101 [Feat]: 푸시알림 에러시 로그만찍도록 변경 (#100)
  src/main/java/io/sobok/SobokSobok/external/firebase/FCMPushService.java
  src/main/java/io/sobok/SobokSobok/notice/ui/NoticeController.java
Labels: 🌱 승헌, 🔥 Feature, 👾 Fix, 🚀 Release, ☠️ High Priority

#103 [Feat]: 유저 디바이스 토큰 및 유저 이름 유니크 제외
  src/main/java/io/sobok/SobokSobok/auth/domain/User.java
Labels: 🌱 승헌, 🔥 Feature, 🚨 Hotfix, ☠️ High Priority

#104 [Feat]: 유저 디바이스 토큰 및 유저 이름 유니크 제외 (#103)
  src/main/java/io/sobok/SobokSobok/auth/domain/User.java
Labels: 🌱 승헌, 🔥 Feature, 🚨 Hotfix, 🚀 Release, ☠️ High Priority

#106 [Feat]: 내 닉네임 조회 API
  src/main/java/io/sobok/SobokSobok/auth/application/UserService.java
  src/main/java/io/sobok/SobokSobok/auth/ui/UserController.java
Labels: 🌱 승헌, 🔥 Feature, ☠️ High Priority

#107 [Feat]: 내 닉네임 조회 API (#106)
  src/main/java/io/sobok/SobokSobok/auth/application/UserService.java
  src/main/java/io/sobok/SobokSobok/auth/ui/UserController.java
Labels: 🌱 승헌, 🔥 Feature, 🚀 Release, ☠️ High Priority

#109 [Fix]: 유저 탈퇴시 관련 데이터 삭제
  src/main/java/io/sobok/SobokSobok/auth/application/AuthService.java
  src/main/java/io/sobok/SobokSobok/friend/infrastructure/FriendRepository.java
  src/main/java/io/sobok/SobokSobok/pill/infrastructure/PillRepository.java
  src/main/java/io/sobok/SobokSobok/sticker/infrastructure/LikeScheduleRepository.java
Labels: 🌱 승헌, 🔥 Feature, 👾 Fix, ☠️ High Priority

#110 [Fix]: 유저 탈퇴시 관련 데이터 삭제 (#109)
  src/main/java/io/sobok/SobokSobok/auth/application/AuthService.java
  src/main/java/io/sobok/SobokSobok/friend/infrastructure/FriendRepository.java
  src/main/java/io/sobok/SobokSobok/pill/infrastructure/PillRepository.java
  src/main/java/io/sobok/SobokSobok/sticker/infrastructure/LikeScheduleRepository.java
Labels: 🌱 승헌, 👾 Fix, 🚀 Release, ☠️ High Priority

#112 [Fix]: 특정날짜 약 일정 조회 에러 처리
  src/main/java/io/sobok/SobokSobok/pill/infrastructure/PillScheduleQueryRepository.java
Labels: 🍀 수현, 🔥 Feature, 👾 Fix, ☠️ High Priority

#113 [Fix]: 특정날짜 약 일정 조회 에러 처리 (#112)
  src/main/java/io/sobok/SobokSobok/pill/infrastructure/PillScheduleQueryRepository.java
Labels: 🍀 수현, 🔥 Feature, 👾 Fix, ☠️ High Priority

#115 [Fix]: 유저 refresh token 발급 로직 수정
  src/main/java/io/sobok/SobokSobok/auth/application/AuthService.java
Labels: 🌱 승헌, 🔥 Feature, 👾 Fix, ☠️ High Priority

#119 Release 2024/03/17 21:48:30
  scripts/deploy.sh
Labels: 🌱 승헌, 👾 Fix, 🚨 Hotfix

#121 [Fix]: 친구 신청 확인 변수명 수정
  src/main/java/io/sobok/SobokSobok/friend/application/FriendService.java
  src/main/java/io/sobok/SobokSobok/friend/ui/FriendController.java
Labels: 🍀 수현, 👾 Fix

#122 Release
  src/main/java/io/sobok/SobokSobok/friend/application/FriendService.java
  src/main/java/io/sobok/SobokSobok/friend/ui/FriendController.java
Labels: 🌱 승헌, 🍀 수현, 👾 Fix, 🚀 Release
